#!/usr/bin/env ruby

require 'bundler'
require 'bundler/friendly_errors'
require 'open3'
require 'tempfile'

def request(url)
  output, error, status = Open3.capture3('curl', '-L', url)
  raise "Error requesting #{url}:\n\n#{error}" if !status.success?
  output
end

def sha_for_ref(ref, owner)
  url = "https://api.github.com/repos/#{owner}/CocoaPods/commits/#{ref}"
  json = request(url)
  json =~ /\A{\s*"sha":\s*"([0-9a-f]{7,40})"/xi
  $1
end

def gemfile_for_ref(ref, owner)
  url = "https://raw.githubusercontent.com/#{owner}/CocoaPods/#{ref}/Gemfile"
  request(url).gsub(/^gemspec$/, "gem 'cocoapods', git: 'https://github.com/#{owner}/CocoaPods', ref: '#{ref}'")
end

def lockfile_for_ref(ref, owner)
  url = "https://raw.githubusercontent.com/#{owner}/CocoaPods/#{ref}/Gemfile.lock"
  request(url).gsub("PATH\n  remote: .\n  specs:\n    cocoapods", <<-LF.strip)
GIT
  remote: https://github.com/#{owner}/CocoaPods
  revision: #{ref}
  ref: #{ref}
  specs:
    cocoapods
  LF
end

def install(ref, owner)
  old_root = Bundler.method(:root)
  def Bundler.root
    Pathname(Bundler::SharedHelpers.pwd).expand_path
  end
  ENV["BUNDLE_GEMFILE"] ||= "Gemfile"

  builder = Bundler::Dsl.new
  builder.instance_eval(gemfile_for_ref(ref, owner))

  definition = nil
  Tempfile.open('Gemfile.lock') do |lockfile|
    lockfile.write(lockfile_for_ref(ref, owner))
    lockfile.rewind
    definition = builder.to_definition(lockfile, {})
  end
  def definition.lock(*); end
  definition.validate_ruby!

  Bundler.ui = Bundler::UI::Silent.new
  definition.resolve_remotely! unless (definition.missing_specs.empty? rescue false)
  def definition.resolve_remotely!; end
  def definition.resolve_with_cache!; end
  Bundler::Installer.install(Bundler.root, definition, :system => true, :update => false)

  runtime = Bundler::Runtime.new(Bundler.root, definition)
  runtime.setup.require

  bundler_module = class << Bundler; self; end
  bundler_module.send(:define_method, :root, old_root)
end

ref, owner = ARGV.shift.split(':', 2).reverse
owner ||= 'CocoaPods'
ref = sha_for_ref(ref, owner)

begin
  install(ref, owner)
rescue => e
  puts e.backtrace
  Bundler.ui = Bundler::UI::Shell.new
  Bundler.with_friendly_errors { raise }
end

load Gem.bin_path('cocoapods', 'pod')
